---
ENV: "dev"
AWS_PROFILE: "saml_dev"

APPNAME: "batchbot"
HOSTNAME: "batchbot.labmed-dev.uw.edu"
INTERNAL_HOST: "batchbot.labmed.internal"
DOKKU_HOST: "dokku-stack-apps-ngs-{{ ENV }}"
STACK_NAME: "app-batchbot-stack-{{ ENV }}"

# deployment variables
CF_TEMPLATES_BUCKET_NAME: "uwlmdev-aws-admin-cf-templates"

# RDS configuration
PGUSER: "batchbotdb"
PGDATABASE: "batchbotdb"
DB_SECURITY_GROUP: "sg-07b60794ab0561d7e"
DB_SUBNET_NAME: "dokku-stack-apps-dbsubnetgroup-15nsk6qorjvfh"
DBI_RESOURCE_ID: "db-WIPIZ3N7J6CSOQK7QSMVEUZOFA"

