"""empty message

Revision ID: 126f0c58bf81
Revises: 16bf426ded22
Create Date: 2019-10-18 14:16:51.948999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126f0c58bf81'
down_revision = '16bf426ded22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_execution', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_execution', 'username')
    # ### end Alembic commands ###
