"""empty message

Revision ID: 16bf426ded22
Revises: 28b427a18ea8
Create Date: 2019-10-16 22:23:58.409548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bf426ded22'
down_revision = '28b427a18ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_execution', sa.Column('cacheTaskArn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_execution', 'cacheTaskArn')
    # ### end Alembic commands ###
