"""empty message

Revision ID: 2700b2b0e97b
Revises: 
Create Date: 2019-09-09 09:12:22.188599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2700b2b0e97b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weblog_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runName', sa.String(), nullable=True),
    sa.Column('runId', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('utcTime', sa.DateTime(), nullable=True),
    sa.Column('metadataField', sa.JSON(), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weblog_event')
    # ### end Alembic commands ###
