"""empty message

Revision ID: 28b427a18ea8
Revises: 
Create Date: 2019-10-15 16:00:04.102686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b427a18ea8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecs_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fargateTaskArn', sa.String(), nullable=True),
    sa.Column('taskArn', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fargateTaskArn', sa.String(), nullable=True),
    sa.Column('taskArn', sa.String(), nullable=True),
    sa.Column('taskId', sa.Integer(), nullable=True),
    sa.Column('taskName', sa.String(), nullable=True),
    sa.Column('taskLogGroupName', sa.String(), nullable=True),
    sa.Column('taskLogStreamName', sa.String(), nullable=True),
    sa.Column('taskLastTrace', sa.JSON(), nullable=True),
    sa.Column('taskLastEvent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weblog_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fargateTaskArn', sa.String(), nullable=True),
    sa.Column('runName', sa.String(), nullable=True),
    sa.Column('runId', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('utcTime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadataField', sa.JSON(), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fargateTaskArn', sa.String(), nullable=True),
    sa.Column('fargateCreatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fargateLastStatus', sa.String(), nullable=True),
    sa.Column('fargateMetadata', sa.JSON(), nullable=True),
    sa.Column('fargateLogGroupName', sa.String(), nullable=True),
    sa.Column('fargateLogStreamName', sa.String(), nullable=True),
    sa.Column('nextflowRunName', sa.String(), nullable=True),
    sa.Column('nextflowMetadata', sa.JSON(), nullable=True),
    sa.Column('nextflowLastEvent', sa.String(), nullable=True),
    sa.Column('nextflowWorkflowStartDateTime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nextflowWorkflowEndDateTime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nextflowExitStatus', sa.String(), nullable=True),
    sa.Column('nextflowIsSuccess', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_execution')
    op.drop_table('weblog_event')
    op.drop_table('task_execution')
    op.drop_table('ecs_event')
    # ### end Alembic commands ###
