"""empty message

Revision ID: 4a4fee1e1ed5
Revises: 532fe89ce34d
Create Date: 2019-10-05 14:38:45.840669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4fee1e1ed5'
down_revision = '532fe89ce34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weblog_event', sa.Column('workflowTaskArn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weblog_event', 'workflowTaskArn')
    # ### end Alembic commands ###
