"""empty message

Revision ID: 532fe89ce34d
Revises: 2700b2b0e97b
Create Date: 2019-10-02 23:30:59.810465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532fe89ce34d'
down_revision = '2700b2b0e97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_runner_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taskArn', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_runner_execution')
    # ### end Alembic commands ###
