"""empty message

Revision ID: 9cb59b9732fe
Revises: e1f04e8948c5
Create Date: 2019-11-20 21:58:59.592339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb59b9732fe'
down_revision = 'e1f04e8948c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_execution', sa.Column('workgroup', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_execution', 'workgroup')
    # ### end Alembic commands ###
