"""empty message

Revision ID: f5dbc97bacad
Revises: 9cb59b9732fe
Create Date: 2019-12-13 21:44:00.842289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5dbc97bacad'
down_revision = '9cb59b9732fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_execution', sa.Column('launchMetadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_execution', 'launchMetadata')
    # ### end Alembic commands ###
